# Generated by Django 4.0 on 2021-12-08 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Corso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome del corso', max_length=100)),
                ('insegnante', models.CharField(help_text='Nome insegnante/tutore', max_length=100)),
                ('livello', models.CharField(help_text='Livello', max_length=100)),
                ('descrizione', models.CharField(help_text='Descrizione corso', max_length=255)),
                ('stato_corso', models.CharField(help_text='Stato corso', max_length=30)),
                ('link_materiale', models.CharField(help_text='Link materiale', max_length=255)),
            ],
        ),
    ]
