# Generated by Django 4.0 on 2021-12-08 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corsi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Serata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome serata', max_length=100)),
                ('descrizione', models.CharField(help_text='Descrizione serata', max_length=255)),
                ('data', models.DateField()),
                ('link_partecipazione', models.CharField(help_text='Link partecipazione', max_length=255)),
                ('link_registrazione', models.CharField(help_text='Link registrazione', max_length=255)),
                ('corso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='corsi.corso')),
            ],
        ),
    ]
